spring:
  application.name: retoJava
  
  datasource:
    url: jdbc:h2:file:./data/retoJavaDb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  jpa.hibernate.ddl-auto: update
